# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02aed88f0d46531b832a4ccabee8dbd7e3e4c1beb303b1fb87f6e4b5a50d8680c0151b090f51d164396fe94b2b20ec27541793bf8ac6554b712a7fe4140c0ac2

test:
  secret_key_base: 6fa560d9a1abe80ebdc2c3019a478e89a3ed353e8f87e3636c9d51aa411eb952e60a5e92756660ec77b3e32fd1f375d79264228562f54105a82a7f244f98e344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
